exports.seed = (knex) => {
  return knex('coral').del()
    .then(() => {
      return knex('coral').insert([
        {
          id: 1,
          name: 'Bubble Tip Anemone',
          scientific_name: 'Entacmaea Quadricolor',
          bio: 'Bubble-tip anemone (Entacmaea quadricolor) is a species of sea anemone in the family Actiniidae. Like several anemone species, E. quadricolor can support several anemonefish species, and displays two growth types based on where they live in the water column, one of which gives it the common name, due to the bulbous tips on its tentacles.',
          warfare: 'Biological/Physical; Anemone produce a sticky, paralysing, venomous cells called nematocysts. If a creature touches a tenticle, it will stick to the creature and as the nematocysts do their job, the anemone can then move the creature to its mouth and swallow it.',
          hardyness: 'Anemone are fairly hardy so long as you introduce them to a mature (6+ months), healthy tank.',
          diet_specifics: 'Anemone generally can eat anything that gets stuck in their tenticles. They are carnivorous and will eat anything from shrimp to whole fish.',
          husbandry: 'In aquariums, E. quadricolor will reproduce asexually or sexually when in proper care with supplemented minerals such as iodine and other trace elements, usually purchased as an enrichment cocktail by most home aquarists.',
          aggressiveness: 'Although they do not actively go looking for fights, they are vicious if something comes into contact with them, they will attack to the best of their ability',
          pictures: '',
          type: 4
        },
        {
          id: 2,
          name: 'Rockflower Anemone',
          scientific_name: 'Phymanthus spp.',
          bio: 'Rock flower anemones stand out from other sea anemones in the structure of their disc. Rather than bringing tentacles all the way to the mouth, the oral disc remains barren. The tentacles stay on the outer fringe, and there are around 200 of them. They are short and feature small ridges that make them look beaded. The center of the disc and the tentacles typically are not the same color.',
          warfare: 'Biological/Physical; Anemone produce a sticky, paralysing, venomous cells called nematocysts. If a creature touches a tenticle, it will stick to the creature and as the nematocysts do their job, the anemone can then move the creature to its mouth and swallow it.',
          hardyness: 'These are fairly hardy anemones that will adapt to a wide variety of lighting conditions. These anemones tend not to wander about the aquarium',
          diet_specifics: 'Anemone generally can eat anything that gets stuck in their tenticles. They are carnivorous and will eat anything from shrimp to whole fish.',
          husbandry: 'One of the best things about the rock flower anemone? No two look alike. Of course, that makes attempting to tell a male and female apart tricky. Good thing the group can reproduce via sexual OR asexual methods. For sexual reproduction, the males and females spawn in autumn. They release the gametes into the water column. The fertilized eggs hatch a granula larva. The granula sinks to the bottom and finds a rock to attach to. It then develops into a polyp that continues to grow. You can also see asexual reproduction. The base will divide, producing a second oral disc. It is similar to the budding you see with coral species. The growth is usually SLOW, and it could take weeks before the new rock flower separates.',
          aggressiveness: 'In general, sea anemones tend to wander. When they do not like the conditions where they are living, they pick up and move on. Rock flower anemones can do the same thing, but they choose not to. They are one of the more sedentary groups out there. Burying themselves in the sand is their M.O. It is one of the reasons their ideal for beginners. You do not need to worry about implementing protective measures around the tank.',
          pictures: '',
          type: 4
        },
        {
          id: 3,
          name: 'Carpet Anemone',
          scientific_name: 'Stichodactyla haddoni',
          bio: 'Stichodactyla haddoni has very small bulbous tentacles that look like little beads that cover the surface. The oral disc diameter is between 50 cm and 80 cm (20 and 31 inches), tentacle-free oral area of 10-20mm (0.4 to 0.8 inches).',
          warfare: 'Biological/Physical; Anemone produce a sticky, paralysing, venomous cells called nematocysts. If a creature touches a tenticle, it will stick to the creature and as the nematocysts do their job, the anemone can then move the creature to its mouth and swallow it.',
          hardyness: 'This Anemone is notoriously hard to keep. It requires a large amount of food and a high concentration of light for their baseline requirements to be met.',
          diet_specifics: 'Anemone generally can eat anything that gets stuck in their tenticles. They are carnivorous and will eat anything from shrimp to whole fish.',
          husbandry: 'Unfortunately, it is almost impossible to breed Stichodactyla sp.in captivity. In nature, these anemones can breed by sexual and asexual means. Sexual reproduction involves sex cells or fertilization of released eggs in the water column. It is really hard to see them spawning because it also depends on the moon cycle. Fertilized eggs produce planula larvae that settles on the sea floor and grows into a new anemone. Asexual reproduction requires only one parent which splits in half from the foot or mouth to form a copy of itself (cloning). Professional aquarists cut them in half and let them heal for a month or two. Please, DO NOT do that in your home aquarium! Without proper technic you will kill the anemone.',
          aggressiveness: 'This anemone anchors itself in the substrate using somehthing large already buried beneath the substrate. It does not go wandering around the tank and so if placed away from everything, should leave everything else alone.',
          pictures: '',
          type: 4
        },
        {
          id: 4,
          name: 'Magnificient Anemone',
          scientific_name: 'Heteractis magnifica',
          bio: 'The magnificent sea anemone is characterized by a flared oral disc, which reaches between 20 and 50 cm in diameter, but in some specimens, this can reach 1 m. The oral disc, the base of the tentacles, and the oral orifice have the same color, going from light beige to white',
          warfare: 'Biological/Physical; Anemone produce a sticky, paralysing, venomous cells called nematocysts. If a creature touches a tenticle, it will stick to the creature and as the nematocysts do their job, the anemone can then move the creature to its mouth and swallow it.',
          hardyness: 'This Anemone is notoriously hard to keep. It requires a large amount of food and a high concentration of light for their baseline requirements to be met.',
          diet_specifics: 'Anemone generally can eat anything that gets stuck in their tenticles. They are carnivorous and will eat anything from shrimp to whole fish.',
          husbandry: 'The reproduction of the anemone can be sexual by simultaneous transmission of male and female gametes in the water or asexual by scissiparity,[5] which means that the anemone divides itself into two individuals, separating from the foot or the mouth.',
          aggressiveness: 'Although they do not actively go looking for fights, they are vicious if something comes into contact with them, they will attack to the best of their ability',
          pictures: '',
          type: 4
        },
        {
          id: 5,
          name: 'Tube Anemone',
          scientific_name: 'Cerianthus membranaceus',
          bio: 'The Tube Anemone Cerianthus membranaceus, also known as the Tube Dwelling Anemone, has some very interesting traits. Being both colorful and hardy, it is prized for an aquarium display. This durable animal that can tolerate a fairly wide temperature range, subdued lighting, and moderate filtration. The Tube Anemone is big, however, reaching 8” (20 cm) across and its tentacles can extend 12" (30.5 cm) or more. It spreads its long outer tentacles over the surface of the mud or sand to capture prey. A good sized aquarium is necessary to accommodate its expansive size and burrowing behavior. It can also produce quite a bit of waste from the excretion of tube slime.',
          warfare: 'Biological/Physical; Anemone produce a sticky, paralysing, venomous cells called nematocysts. If a creature touches a tenticle, it will stick to the creature and as the nematocysts do their job, the anemone can then move the creature to its mouth and swallow it.',
          hardyness: 'Coming from temperate waters, Tube Anemones can be moderate to care for. They are best kept by intermediate to advanced aquarists as they have specific needs. This tube anemone needs a cold water environment and they require a lot of space. They need a large enough aquarium to satisfy their burrowing behavior and their ultimate size, and the temperature needs to be kept between 59 to 72° F (15 to 22°C), which that requires a chiller',
          diet_specifics: 'Anemone generally can eat anything that gets stuck in their tenticles. They are carnivorous and will eat anything from shrimp to whole fish.',
          husbandry: 'There is no information yet on breeding Tube Anemone in captivity. In nature, the C. membranaceus reproduce sexually with the female being larger than the male. Unlike the true anemones, they do not reproduce through asexual means such as fission, where the anemone is divided or split into parts to create a new anemone. Tube Anemones are hermaphrodites, meaning they are both male and female. Although each animal can produce both eggs and sperm, they do not produce them at the same time, so it takes two specimens to produce a zygote. The Zygote is a fertilized egg, the beginnings of a new tube anemone. There is no information yet on breeding these anemones in captivity.',
          aggressiveness: 'As this is a sedantary species, other tank mates should be fine so long as it is isolated away from everything else.',
          pictures: '',
          type: 4
        },
        {
          id: 6,
          name: 'Zoanthid',
          scientific_name: 'Zoanthus sp.',
          bio: 'Species form this genus are the most colorful, they possess contrasting shades of green and brown mostly, but sometimes red, orange, pink, blue, yellow, lavender, grey, and are usually two-toned. They form colonies of densely crowded polyps attached in a common tissue at the base, while some varieties form branched stolon-like creeping bases that firmly adhere to the substrate surface.',
          warfare: 'Chemical; when iritated, zoanthids can excrete or shoot a toxin from thier mouth. This toxin is called palytoxin and can make a human very sick.',
          hardyness: 'Zoanthids are easy to keep beginner coral with low requirements that are easy to provide for.',
          diet_specifics: 'According to an article on Chaos Aquaculture, zoanthids enjoy eating specialized coral food, as well as simple foods such as brine shrimp, copepods, and rotifers. Zoanthids also enjoy amino acid and vitamin supplements. However, feeding is not required as zoas are photosynthetic. Therefore, if you are not feeding other coral, it may be best to not worry about feeding',
          husbandry: 'Zoanthids tend to reproduce via budding, so for reproduction to occur, you just need to make sure the coral colony is happy and thriving.',
          aggressiveness: 'Zoanthids are not an aggressive coral, but placement can drive your success and growth rate. Beyond flow and lighting, zoanthids should be placed on flat surfaces. Zoas grow by spreading outward and struggle to grow on rocks that are too porous. By placing zoas on flat surfaces, you allow these zoanthids to grow more easily, and quickly.',
          pictures: '',
          type: 1
        },
        {
          id: 7,
          name: 'Star Polyps',
          scientific_name: 'Pachyclavularia sp.',
          bio: 'Green Star Polyps are easy to raise, spread easily, and can be found both online or in pet shops. Love them or hate them, it is not possible to deny that they can also be extremely fluorescent and attractive in a reef aquarium where they look like hills of grass swaying in the wind.',
          warfare: 'They do not have a means of defense',
          hardyness: 'The waters they are found in usually have low water flow and are high in nutrients. When we are talking about nutrients, we usually mean all kinds of things like suspended food particles, elements the foods break down into, for example, amino acids as well as the end result with nitrates and phosphate. Along with knowing how to keep your Green Star Polyps healthy, you should also know how to limit them. Green Star Polyps can grow out of control if you do not take steps to limit their growth. Actually, they are pretty invasive.',
          diet_specifics: 'In general, you do not have to worry about feeding them in the reef set up. Green Star Polyps will perfectly well underneath the lights that you have in your tank. However, if you want them to grow even faster and you want them to have some better color on them I would definitely recommend feeding some liquid food to them.',
          husbandry: 'This coral can be like a weed and so you are more likely to ',
          aggressiveness: 'Start polyps are very peaceful with no means to defend themselves.',
          pictures: '',
          type: 1
        },
        {
          id: 8,
          name: 'Kenya Tree',
          scientific_name: 'Capnella spp.',
          bio: 'This species is arborescent, i.e. resembling a tree. Kenya tree corals possess several lateral branches that are heavily forked. The branches grow out from a thick trunk, and they sway gently in the aquarium water. These corals can grow really large and can reach up to 12 inches (30 cm) in diameter. Though Kenya tree corals are not stony corals, they possess rigid structures called sclerites. These are composed of calcium carbonate, and their role is to provide structural support for the animal.',
          warfare: 'The Kenya tree corals, Capnella spp., are known for several behaviors, especially hostile tendencies and easy propagation. They are often considered semi-aggressive, and it is not unusual for Kenya trees to attack nearby corals by releasing some chemical toxins in the battle for real estate. Kenya trees corals lack the sweeper tentacles found in many aquarium corals, so they often resort to the toxic substances in their arsenal to ward off predatory species and competitors. Studies have revealed that these substances are similar to terpenes emitted by toadstool corals. Terpenes are capable of limiting growth in organisms by impacting cellular division. ',
          hardyness: 'Kenya tree coral is a hardy, beginner-friendly species of soft corals that can thrive in a range of aquarium conditions. However, it would help if you were cautious while keeping this coral as it can reproduce quickly. You are required to closely observe the colony and prune the coral when they are too grown or excess in number. In the same vein, make sure to scout for fragments or buds growing on undesirable areas and remove them; else, they will overpopulate and overrun your reef tank. Kenya tree coral does not need pristine water conditions to grow and thrive. They will appreciate water with lots of dissolved nutrients to feed off, so you do not have to maintain very clean water.',
          diet_specifics: 'Kenya tree coral receives some nutrition with the aid of the symbiotic algae (zooxanthellae) living in their soft tissue. They also feed by absorbing dissolved nutrients and trapping micro planktons and organic matter from the water column. Though they obtain nourishment through the symbiotic algae that live within their tissue, it will not be enough to make them grow optimally. That said, they need supplemental target feeding at least once a week.',
          husbandry: 'Kenya tree coral will spread all over the aquarium. They are capable of budding and fragmentation, i.e. releasing tiny parts or buds of the parent colony; these will break away and move to different areas of the reef tank, then grow and develop into a polyp.',
          aggressiveness: 'Since this species is known to release chemical substances into the water as a defense mechanism. Therefore, you must engage in frequent water changes to remove/dilute it. You may as well fit activated carbon media into the filter to inhibit the potency of this harmful chemical.',
          pictures: '',
          type: 1
        },
        {
          id: 9,
          name: 'Riccordea',
          scientific_name: 'Ricordea florida and Ricordea yuma',
          bio: 'Ricordea corals are known for their unique bubble-like appearance, fleshy body, and brightly colored tentacles that come in a variety of color combinations including blue, green, yellow, pink, purple, and orange. And they exhibit fluorescence under full actinic lighting.',
          warfare: 'Physical; Riccordea produce a sting when their tenticles are touched',
          hardyness: 'Much of the care routine is centered on keeping the aquarium water clean, promoting stability, and maintaining excellent water quality to encourage optimal health and survival of your Ricordea corals.',
          diet_specifics: 'As with other marine corals, Ricordea derives much of its energy from the products of the symbiotic algae zooxanthellae living in its tissue. Mutualistic relationship with the zooxanthellae allows Ricordea coral to obtain nutrition through the process of photosynthesis. Ricordea corals can also filter-feed, hence they are capable of straining suspended matter, food particles, and dissolved organic matter from the aquarium water.',
          husbandry: 'In nature, Ricordea corals have two ways of reproduction: -Sexually by producing planula larvae through the fertilization of the male and female gametes. These larvae then settle onto the bottom and gradually metamorphose into new individual polyps. -Asexually. They are also capable of asexual reproduction, and this type of reproduction is very common in the reef aquarium. Ricordea corals can increase their numbers asexually through two known methods: longitudinal fission and pedal laceration. Longitudinal fission takes places when the coral develops multiple mouths, and then splits in the center thereby separating into two individual polyps. An alternative method is pedal laceration whereby the coral leaves pieces of their foot behind while moving around, and these pieces will grow into new full-sized polyps',
          aggressiveness: 'It is a semi-aggressive coral and as such, needs to be adequately spaced out from other corals especially LPS corals with long sweeper tentacles. Ricordea corals lack this kind of tentacles, but they can equally deliver fairly potent stings using their bubbly tentacles to corals in close proximity.',
          pictures: '',
          type: 1
        },
        {
          id: 10,
          name: 'Rhodactis',
          scientific_name: 'Rhodactis sp.',
          bio: 'Rhodactis mushroom corals are corallimorphs of the order Corallimorpharia. They are an oddity in terms of classification. Because of their soft bodies and lack of a skeleton they often associated with soft corals or even anemones, but in terms of taxonomy have more in common with stony corals.',
          warfare: 'Physical; Rhodactis produce a sting when their tenticles are touched',
          hardyness: 'They are great additions to reef aquariums ranging from beginning hobbyists looking for something very hardy to the discerning coral collector that is looking for a signature piece in their hype beast collection.',
          diet_specifics: 'When it comes to nutrition, just providing light for photosynthesis is adequate, but it is possible to spot feed them if you shut off the pumps and are patient.',
          husbandry: 'In home aquariums these mushrooms reproduce asexually through longitudinal fission. In essence that means that they start to develop two mouths and then pinch themselves in half to form two separate mushrooms. It is a lengthier process than say Discosoma that asexually spread through pedal laceration where the coral drops off bits of its foot behind to spawn new mushrooms.',
          aggressiveness: 'It is a semi-aggressive coral and as such, needs to be adequately spaced out from other corals especially LPS corals with long sweeper tentacles. Rhodactis corals lack this kind of tentacles, but they can equally deliver fairly potent stings using their bubbly tentacles to corals in close proximity.',
          pictures: '',
          type: 1
        },
        {
          id: 11,
          name: 'Acan LH',
          scientific_name: 'Micromussa Lord-Howensis',
          bio: 'Acan Corals or Acans (Micromussa lordhowensis) are a group of large poly stony (LPS) corals that are very popular in the reef aquarium hobby because of their vivid color combinations, hardiness, and ease of care.',
          warfare: 'Physical; Acan corals, when they detect a close enough threat, project their stomach (mesenterial filaments) onto the threat and digest them from outside of their bodies.',
          hardyness: 'Acans are also renowned for their fast growth rate, tolerance, and the ability to easily adapt to a new reef environment. All these remarkable features make it an excellent choice for reef hobbyists.',
          diet_specifics: 'Just like other animals in the class Anthrozoa, Acan corals receive a great portion of their nutrition through photosynthesis from their symbiotic relationship with the zooxanthellae algae. In a well-established reef aquarium, Acans can also feed through the water column by consuming the phytoplankton and zooplankton suspended in the tank water. However, regular feeding should be a priority, they should be fed every 2 or 3 days. Acans are more active at night when your fish are asleep. They will extend their tentacles to collect meals.',
          husbandry: 'Large poly stony corals including Acans corals are hermaphrodites, meaning that they possess male and female gametes within the same organism, and they can also reproduce both sexually and asexually. Acans corals are broadcast spawners, in the wild, they reproduce by releasing eggs and sperm at the same time which results in a fertilized egg, this develops into a free-swimming planula larva. After a while, the larva will settle onto the substrate, becoming planksters. Eventually, the larva will metamorphose into a tiny polyp which begins to excrete calcium carbonate, thus developing into a coral.',
          aggressiveness: 'Polyps from the genus Mircromussa are generally peaceful towards other coral species, they do extend tentacles in order to feed and can damage other corals. Therefore, they should be properly distanced or kept away from other corals. These corals will extend their stomachs at night to attack corals nearby.',
          pictures: '',
          type: 2
        },
        {
          id: 12,
          name: 'Blasto',
          scientific_name: 'Blastomussa Wellsi',
          bio: 'Blastomussa are an interesting stony coral because from afar they resemble mushroom corallimorphs.',
          warfare: 'Physical; Blastomussa have sweeper tenticles that they can use to fend off other coral from their territory',
          hardyness: 'These corals are fairly hardy, they will tolerate the odd swing in parameters, making them perfect for someone moving up from softies to LPS.',
          diet_specifics: 'Like many of our other LPS, feeding is a major key to the long term success of keeping Blastos. Blastomussa can be fed a mix of meaty foods such as pieces of krill or mysis shrimp.',
          husbandry: 'In terms of propagation, Blastomussa have been successfully fragmented and are an excellent candidate for aquaculture.',
          aggressiveness: 'Though they have sweeper tenitcles, they are not considered aggressive as their sting is not very strong. In coral war-fare, the Blasto is likely to loose, so adequate space away from aggressive corals should be given to this coral to allow for a good amount of growth.',
          pictures: '',
          type: 2
        },
        {
          id: 13,
          name: 'Torch Coral',
          scientific_name: 'Euphyllia glabrescens',
          bio: 'The Torch coral is a popular large polyp stony (LPS) coral species notable for its long fleshy tentacles that sway in the tank. These fleshy tentacles have round tips with contrasting colors that make it look like a torch within the reef tank, hence the name Torch coral.',
          warfare: 'Biological/Physical; Torch coral defend themselves using nematocysts. They are found in the tenticles themselves.',
          hardyness: 'Torch corals are not easy to take care of. It is challenging but not impossible, and very rewarding when everything goes well. Always endeavor to make partial water changes of either 20 to 25% monthly, 10 to 15% bi-weekly, or 5% weekly to maintain good water quality and replenish the needed trace elements.',
          diet_specifics: 'As with all other LPS corals, Torch corals have a symbiotic relationship with zooxanthellae hosting in their tissue and this enables them to obtain nutrients through photosynthesis. Although this feeding mechanism ensures they get enough nutrients to survive, Torch corals would also benefit hugely from supplemental or manual feeding.',
          husbandry: 'Torch corals are capable of carrying out sexual and asexual reproduction. In the wild, the corals will release mature gametes (eggs and sperm) into the water, fertilization takes place, and this will give rise to coral larvae, otherwise known as planulae. Under the right conditions, the free-swimming planulae will metamorphose into polyps that will attach themselves to the surface they have settled on. In asexual reproduction, the mature polyps reproduce by budding. This enables smaller polyps to form around the base, these polyps will remain connected to the colony or break-off in response to environmental conditions to establish a new colony. If you see long strings coming out of the Torch coral, do not worry, it just a sign that its heads are about to split soon. Another means of propagation is through the fragging of a healthy coral.',
          aggressiveness: 'Torch corals are sessile and generally aggressive, and they will tend to compete with other corals for space in the reef tank. A rule of thumb is to leave plenty of space in between your torches and any other coral or tankmates in the aquarium. This is important as they possess cnidocyte, an explosive cell containing a giant secretory organelle known as nematocyst, and this is used by the corals to deliver a painful sting to competitors or nearby organisms. In essence, these stinging cells help Torch corals immobilize and capture prey in their environment, and it also serves as a defensive mechanism against predators.',
          pictures: '',
          type: 2
        },
        {
          id: 14,
          name: 'Frogspawn',
          scientific_name: 'Euphyllia divisa',
          bio: 'The name Frogspawn was coined from its attractive multi-tipped tentacles that bear a striking resemblance to a mass of frog eggs.',
          warfare: 'Biological/Physical; Frogspawn coral defend themselves using nematocysts. They are found in the tenticles themselves.',
          hardyness: 'Regular inspection and a good water change schedule are essential in ensuring good health of the corals and optimal water chemistry. Maintain the following trace elements and compounds in the right proportions to promote the best growth conditions.',
          diet_specifics: 'Regardless of the presence and role of the photosynthetic zooxanthellae, they should also be fed live and meaty frozen food. Through supplemental or manual feeding, the corals will grow more vigorously, so do not assume that the nutrition they get from photosynthesis is enough to make them attain rapid growth spurt and gain enormous mass.',
          husbandry: 'Frogspawn corals can reproduce through sexual and asexual means. In the wild, they carry out sexual reproduction by releasing gametes into the water, resulting in a fertilized egg which eventually gives rise to a free-swimming planula larva. Afterward, the planula larva will metamorphose to a tiny polyp which begins to excrete calcium carbonate, thus developing into a coral. Moreover, Frogspawn corals are capable of reproducing asexually. As seen in reef aquariums, a Frogspawn coral will bud off a small group of polyps with little skeletons present. It usually takes them a few months to turn into full-sized heads. They will also break-off individual polyps in response to stress, these polyps will relocate elsewhere and start a new colony. Another method is through coral fragging. However, it can be a little bit tricky because, as I have mentioned earlier, there are two types of Frogspawn corals: the wall type and the branching type.',
          aggressiveness: 'Euphyllia corals can be quite aggressive when placed in close proximity to other corals, as they tend to battle/compete for real estate in your aquarium. Therefore they should be adequately spaced from other corals in the tank. Frogspawn coral are hostile but not to the species in its own genus, however, corals of other genera in the family Euphylliidae are not exempted from this hostility. As observed, the polyps extend during the day and only partially at night. Their sweeper tentacles can extend up to 25 cm in larger colonies when they witness hunger pangs, this poses a threat to nearby corals because of the powerful sting they can deliver.',
          pictures: '',
          type: 2
        },
        {
          id: 15,
          name: 'Hammer Coral',
          scientific_name: 'Euphyllia ancora',
          bio: 'The Hammer coral has a calcified skeletal base, and the colonies have the same skeletal structure as Euphyllia divisa (Frogspawn coral) although the tentacles are quite different.',
          warfare: 'Biological/Physical; Hammer coral defend themselves using nematocysts. They are found in the tenticles themselves.',
          hardyness: 'Regular inspection and a good water change schedule are essential in ensuring good health of the corals and optimal water chemistry. Maintain the following trace elements and compounds in the right proportions to promote the best growth conditions.',
          diet_specifics: 'Regardless of the presence and role of the photosynthetic zooxanthellae, they should also be fed live and meaty frozen food. Through supplemental or manual feeding, the corals will grow more vigorously, so do not assume that the nutrition they get from photosynthesis is enough to make them attain rapid growth spurt and gain enormous mass.',
          husbandry: 'Hammer corals can reproduce through sexual and asexual means. In the wild, they carry out sexual reproduction by releasing gametes into the water, resulting in a fertilized egg which eventually gives rise to a free-swimming planula larva. Afterward, the planula larva will metamorphose to a tiny polyp which begins to excrete calcium carbonate, thus developing into a coral. Moreover, Frogspawn corals are capable of reproducing asexually. As seen in reef aquariums, a Frogspawn coral will bud off a small group of polyps with little skeletons present. It usually takes them a few months to turn into full-sized heads. They will also break-off individual polyps in response to stress, these polyps will relocate elsewhere and start a new colony. Another method is through coral fragging. However, it can be a little bit tricky because, as I have mentioned earlier, there are two types of Frogspawn corals: the wall type and the branching type.',
          aggressiveness: 'Euphyllia corals can be quite aggressive when placed in close proximity to other corals, as they tend to battle/compete for real estate in your aquarium. Therefore they should be adequately spaced from other corals in the tank. Hammer coral are hostile but not to the species in its own genus, however, corals of other genera in the family Euphylliidae are not exempted from this hostility. As observed, the polyps extend during the day and only partially at night. Their sweeper tentacles can extend up to 25 cm in larger colonies when they witness hunger pangs, this poses a threat to nearby corals because of the powerful sting they can deliver.',
          pictures: '',
          type: 2
        },
        {
          id: 16,
          name: 'Acropora',
          scientific_name: '',
          bio: '',
          warfare: '',
          hardyness: '',
          diet_specifics: '',
          husbandry: '',
          aggressiveness: '',
          pictures: '',
          type: 3
        },
        {
          id: 17,
          name: 'Stylophora',
          scientific_name: '',
          bio: '',
          warfare: '',
          hardyness: '',
          diet_specifics: '',
          husbandry: '',
          aggressiveness: '',
          pictures: '',
          type: 3
        },
        {
          id: 18,
          name: 'Seriatapora',
          scientific_name: '',
          bio: '',
          warfare: '',
          hardyness: '',
          diet_specifics: '',
          husbandry: '',
          aggressiveness: '',
          pictures: '',
          type: 3
        },
        {
          id: 19,
          name: 'Montipora',
          scientific_name: '',
          bio: '',
          warfare: '',
          hardyness: '',
          diet_specifics: '',
          husbandry: '',
          aggressiveness: '',
          pictures: '',
          type: 3
        },
        {
          id: 20,
          name: 'Pocillopora',
          scientific_name: '',
          bio: '',
          warfare: '',
          hardyness: '',
          diet_specifics: '',
          husbandry: '',
          aggressiveness: '',
          pictures: '',
          type: 3
        }
      ])
    })
}
